### json update
POST http://localhost:8080/update/
Content-Type: application/json

{
    "id": "Alloc",
    "type": "gauge",
    "value": 123.45
}


### ++
POST http://localhost:8080/update/counter/name1/50

### <
POST http://localhost:8080/update/gauge/name2/3.14

### <
POST http://localhost:8080/update/gauge/someMetric/3.15

### all
POST http://localhost:8080/metrics

### html
GET http://localhost:8080/

### get Some by type and name
GET  http://localhost:8080/value/gauge/Alloc

### get Some by type and name
GET  http://localhost:8080/value/counter/PollCount

### ошибка http.StatusNotFound.
POST http://localhost:8080/update/counter/527

### ошибка POST only
GET http://localhost:8080/update/counter/527

### ошибка http.StatusNotFound.
POST http://localhost:8080/update/counter/527

### ошибка 
GET http://localhost:8080/update/undo/tres/527



### 
POST  http://localhost:8080/value/
#HashSHA256: dcf537b9e9b674c850fc34bebc775123f5d3d2e78f069d36ac56218ba20c2875

{
    "id":"PollCount",
    "type":"counter"
}

### 
POST  http://localhost:8080/value/
//HashSHA256: e129199726523d06ef4fd11f740b1102739fcf88a356b62f6072e5194629a3d6

{
    "id":"RandomValue", 
    "type":"gauge"
}

### 
POST  http://localhost:8080/value/
//HashSHA256: a118aa2d289c319789ddade48703e22b5986302d50077ec29bf58aca907e84ba

{"id": "PollCount", "type": "counter"}


### 
GET  http://localhost:8080/value/counter/testSetGet12

### get_unknown
GET http://localhost:8080/value/gauge/testUnknown251

### ping db
GET http://localhost:8080/ping

### 
POST  http://localhost:8080/update/
HashSHA256: 1f8b08000000000000ff86d7b789c0be1e82055317a290dea5018854377b65c26d54041551a57fdc9a9e

{"id":"PollCount","type":"gauge","value":1}


### 
POST  http://localhost:8080/update/
HashSHA256: 1f8b08000000000000ff86d7b789c0be1e82055317a290dea5018854377b65c26d54041551a57fdc9a9e

{"id":"NumForcedGC","type":"counter", "delta":3}